version: "3.6"
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"

  api:
    container_name: api
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/api
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    environment:
      - GIN_MODE=release
    depends_on:
      - elastic
    ports:
      - 127.0.0.1:14000:14000
    logging: *my-logging

  indexer:
    container_name: indexer
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/indexer
    build:
      context: .
      dockerfile: cmd/indexer/Dockerfile
    depends_on:
      - elastic
    logging: *my-logging

  mq:
    container_name: mq
    hostname: mq
    image: rabbitmq:latest
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    logging: *my-logging

volumes:
  esdata:
