version: "3.6"
services:
  elastic:
    image: ghcr.io/baking-bad/bcdhub-elastic:${TAG}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  db:
    image: postgres:12
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=indexer
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: *bcd-logging

  api:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-api:${TAG}
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - db
    ports:
      - 127.0.0.1:14000:14000
    volumes:
      - bcdshare:/etc/bcd
    links:
      - "flextesa:sandbox"
    logging: *bcd-logging

  indexer:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-indexer:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - db
      - metrics
    links:
      - "flextesa:sandbox"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-metrics:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - db
    links:
      - "flextesa:sandbox"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  flextesa:
    restart: always
    image: tqtezos/flextesa:20211206
    command: hangzbox start --keep-root
    environment:
      - block_time=4
      - flextesa_node_cors_origin=*
    ports:
      - 127.0.0.1:20000:20000
    expose:
      - 20000/tcp
    logging: *bcd-logging
    volumes:
      - flextesa:/tmp/mini-box

  gui:
    container_name: sandbox-gui
    restart: always
    image: ghcr.io/baking-bad/bcdhub-gui:${TAG}
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
      - 172.17.0.1:8000:80
    logging: *bcd-logging

  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  esdata:
  bcdshare:
  flextesa:
  db:
    driver: local